/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#65645e",
        "secondary-fixed-dim": "#c9c6be",
        "surface-container-highest": "#d6e6e1",
        "secondary-container": "#e5e2d9",
        "surface-container-high": "#dbece6",
        "surface-container": "#e1f1ec",
        "surface-variant": "#d6e6e1",
        "inverse-surface": "#253330",
        "surface-container-low": "#e7f7f2",
        "background": "#edfdf8",
        "tertiary": "#451e00",
        "outline": "#707977",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#7bb5ac",
        "surface-bright": "#edfdf8",
        "on-background": "#101e1b",
        "on-secondary": "#ffffff",
        "surface": "#edfdf8",
        "secondary": "#5f5f58",
        "primary": "#002f2a",
        "error-container": "#ffdad6",
        "primary-fixed": "#b3eee5",
        "secondary-fixed": "#e5e2d9",
        "primary-fixed-dim": "#97d2c9",
        "on-primary-fixed": "#00201d",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#723600",
        "primary-container": "#004741",
        "surface-dim": "#cdded8",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#1c1c17",
        "on-surface": "#101e1b",
        "on-tertiary-fixed": "#311300",
        "on-secondary-fixed-variant": "#484741",
        "on-error-container": "#93000a",
        "tertiary-container": "#663000",
        "tertiary-fixed": "#ffdcc6",
        "inverse-primary": "#97d2c9",
        "tertiary-fixed-dim": "#ffb786",
        "on-primary": "#ffffff",
        "outline-variant": "#bfc8c6",
        "on-surface-variant": "#404947",
        "surface-tint": "#2e6861",
        "on-tertiary-container": "#f69146",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#e4f4ef",
        "on-primary-fixed-variant": "#0f4f49",
        "cream": "#F0EDE4",
        "forest-dark": "#003631"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "margin": "2rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-2xl": "4rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "sans": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-hero": ["52px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "label-lg": ["16px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["34px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    }
  },
  plugins: []
};
